# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seed < Formula
  desc "Plant the seeds of your directory tree 🌱"
  homepage "https://github.com/jpwallace22/seed"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpwallace22/seed/releases/download/v0.1.4/seed_0.1.4_darwin_amd64.tar.gz"
      sha256 "fd8c1c04fac8530db7fa2e5f1b7cfe9b23ec10c3c6d44fbefc069cd83fa37a9c"

      def install
        bin.install "seed"
        system "#{bin}/seed", "man", man1
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpwallace22/seed/releases/download/v0.1.4/seed_0.1.4_darwin_arm64.tar.gz"
      sha256 "c6c406cf0ba9d36ae0c5f1363c09e1ebb8f98c45704fb2fd8aae0d005fbe5e40"

      def install
        bin.install "seed"
        system "#{bin}/seed", "man", man1
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jpwallace22/seed/releases/download/v0.1.4/seed_0.1.4_linux_amd64.tar.gz"
        sha256 "d7df466f1aa045d2a09289ed0214c8e9fe518e17079f5a1ae3a342d5fefaa4c0"

        def install
          bin.install "seed"
          system "#{bin}/seed", "man", man1
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jpwallace22/seed/releases/download/v0.1.4/seed_0.1.4_linux_arm64.tar.gz"
        sha256 "65ed3ecf2ac666048d6db7872adb3c387004f050f40a799931bf5cd5f784a380"

        def install
          bin.install "seed"
          system "#{bin}/seed", "man", man1
        end
      end
    end
  end

  test do
    system "#{bin}/seed --version"
  end
end
